module.exports =
  saturation: require './tools/saturation'
  temperature: require './tools/temperature'
  brightness: require './tools/brightness'
  scale: require './tools/scale'
  crop: require './tools/crop'
  orientation: require './tools/orientation'
  text: require './tools/text'
  contrast: require './tools/contrast'
  sepia: require './tools/sepia'
  greyscale: require './tools/greyscale'
  sharpness: require './tools/sharpness'